---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-binaries
  image: golang:1.12
  commands:
  - make build build-dev
  environment:
    REVISION: "${DRONE_COMMIT}"
    VERSION: DEV
  when:
    event:
    - push

- name: build-docker
  image: plugins/docker
  settings:
    build_args:
    - VER=DEBUG
    dry_run: true
    repo: danmx/sigil
    tags:
    - debug
    target: debug
  when:
    event:
    - push

- name: build-release
  image: golang:1.12
  commands:
  - make build
  environment:
    REVISION: "${DRONE_COMMIT}"
    VERSION: "${DRONE_TAG}"
  when:
    event:
    - tag

- name: docker-release
  image: plugins/docker
  settings:
    auto_tag: true
    build_args:
    - "VER=\"${DRONE_TAG}\""
    password:
      from_secret: docker_password
    repo: danmx/sigil
    target: prod
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: github-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha1
    - sha256
    - sha512
    files:
    - "bin/release/*"
  when:
    event:
    - tag

---
kind: signature
hmac: c5d1fc4ed9927d6d609372c169a0865745eb335137991718bd07ff3f20763d66

...
