---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: l.gcr.io/google/bazel:3.4.1
  commands:
  - bazel test --config cross:linux_amd64 //...
  volumes:
  - name: cache
    path: /root/.cache/bazel/

- name: coverage
  image: l.gcr.io/google/bazel:3.4.1
  commands:
  - bazel coverage --config cross:linux_amd64 //...
  - bazel build --config cross:linux_amd64 :concat-cov
  volumes:
  - name: cache
    path: /root/.cache/bazel/

- name: codecov
  image: plugins/codecov
  settings:
    files:
    - bazel-bin/coverage.txt
    required: true
    token:
      from_secret: codecov_token
  volumes:
  - name: cache
    path: /root/.cache/bazel/

- name: build-dev
  image: l.gcr.io/google/bazel:3.4.1
  commands:
  - bazel build --config cross:linux_amd64 :dev
  - bazel build --config cross:darwin_amd64 :dev
  - bazel build --config cross:windows_amd64 :dev
  - bazel build --config cross:linux_amd64 :dev-image
  environment:
    GIT_BRANCH: ${DRONE_BRANCH}
    GIT_COMMIT: ${DRONE_COMMIT}
    VERSION: DEV
  volumes:
  - name: cache
    path: /root/.cache/bazel/
  when:
    event:
    - push

- name: docker-dev
  image: l.gcr.io/google/bazel:3.4.1
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - bazel run --config cross:linux_amd64 :push-dev-image
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: cache
    path: /root/.cache/bazel/
  when:
    event:
    - push

- name: pkg-release
  image: l.gcr.io/google/bazel:3.4.1
  commands:
  - bazel build --config cross:linux_amd64 :sigil_linux-amd64
  - bazel build --config cross:darwin_amd64 :sigil_darwin-amd64
  - bazel build --config cross:windows_amd64 :sigil_windows-amd64
  environment:
    GIT_BRANCH: ${DRONE_BRANCH}
    GIT_COMMIT: ${DRONE_COMMIT}
    VERSION: ${DRONE_TAG}
  volumes:
  - name: cache
    path: /root/.cache/bazel/
  when:
    event:
    - push
    - tag

- name: docker-release
  image: l.gcr.io/google/bazel:3.4.1
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - bazel run --config cross:linux_amd64 :push-release-image
  - bazel run --config cross:linux_amd64 :push-major-release-image
  - bazel run --config cross:linux_amd64 :push-minor-release-image
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: cache
    path: /root/.cache/bazel/
  when:
    event:
    - tag

- name: github-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha1
    - sha256
    - sha512
    files:
    - bazel-bin/sigil_linux-amd64.tar.gz
    - bazel-bin/sigil_darwin-amd64.tar.gz
    - bazel-bin/sigil_windows-amd64.zip
    title: ${DRONE_TAG}
  volumes:
  - name: cache
    path: /root/.cache/bazel/
  when:
    event:
    - tag

volumes:
- name: cache
  temp: {}

---
kind: signature
hmac: d1c4660d7762e670ae867b0a3cfb73b1e26ccd560a6562b8b2b9fd2d7ca2f9a4

...
