---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12
  commands:
  - make test

- name: build-binaries
  image: golang:1.12
  commands:
  - make build build-dev
  environment:
    REVISION: "${DRONE_COMMIT}"
    VERSION: DEV
  when:
    event:
    - push

- name: build-docker
  image: plugins/docker
  settings:
    build_args:
    - VER=DEBUG
    - "REV=\"${DRONE_COMMIT}\""
    dry_run: true
    repo: danmx/sigil
    tags:
    - debug
    target: debug
  when:
    event:
    - push

- name: build-release
  image: golang:1.12
  commands:
  - make release
  environment:
    REVISION: "${DRONE_COMMIT}"
    VERSION: "${DRONE_TAG}"
  when:
    event:
    - tag

- name: docker-release
  image: plugins/docker
  settings:
    auto_tag: true
    build_args:
    - "VER=\"${DRONE_TAG}\""
    - "REV=\"${DRONE_COMMIT}\""
    password:
      from_secret: docker_password
    repo: danmx/sigil
    target: prod
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: github-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha1
    - sha256
    - sha512
    files:
    - "dist/*"
  when:
    event:
    - tag

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.txt
    required: true
    token:
      from_secret: codecov_token

---
kind: signature
hmac: 1ac943933c88626b82ce68104c94fdeade49129515d2bb3c7cebac8e83f13127

...
