# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sigil < Formula
  desc ""
  homepage ""
  version "0.7.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zendesk/sigil/releases/download/0.7.4/sigil_0.7.4_Darwin_arm64.tar.gz"
      sha256 "b838ebee4a5926f93ab5e5bbe95dbb47d663ad11351f03fbf15544d9b68fd9d7"

      def install
        bin.install "sigil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zendesk/sigil/releases/download/0.7.4/sigil_0.7.4_Darwin_x86_64.tar.gz"
      sha256 "849277a3e09c4886be3e46ba1e7a08608d8eb513064dce5b60adf993f39a14f6"

      def install
        bin.install "sigil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zendesk/sigil/releases/download/0.7.4/sigil_0.7.4_Linux_arm64.tar.gz"
      sha256 "c6b85ad93323e2f33502067fbb8a1163fae09759edac03fd2c465c444681ab06"

      def install
        bin.install "sigil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zendesk/sigil/releases/download/0.7.4/sigil_0.7.4_Linux_x86_64.tar.gz"
      sha256 "a3fd25dfd4fa358d08e65e9f9bd9c24cd05531d3c51f9d06cb2cf86d2d1eaf0b"

      def install
        bin.install "sigil"
      end
    end
  end
end
