# This file was generated by GoReleaser. DO NOT EDIT.
class Sigil < Formula
  desc ""
  homepage ""
  version "0.7.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zendesk/sigil/releases/download/0.7.2/sigil_0.7.2_Darwin_x86_64.tar.gz"
    sha256 "0400306957ac0aa21fd8d7b8036ccd53553bc3e14f6c2f3a91be6573fba55614"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zendesk/sigil/releases/download/0.7.2/sigil_0.7.2_Linux_x86_64.tar.gz"
    sha256 "ee527fa3d9cbfe48b0bd6bd125f72f29c84924feb0a6410afc8001d9ee6931f5"
  end

  def install
    bin.install "sigil"
  end
end
