# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sigil < Formula
  desc ""
  homepage ""
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zendesk/sigil/releases/download/v0.8.1/sigil_0.8.1_Darwin_x86_64.tar.gz"
      sha256 "abcf854e1d6f26f2786fd871df20cbacdbabe94f5d5662aa8b7cd37c2f987eed"

      def install
        bin.install "sigil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zendesk/sigil/releases/download/v0.8.1/sigil_0.8.1_Darwin_arm64.tar.gz"
      sha256 "e0d9808f993013b065b3d92260a00e042dd7fdd929058bcf8876cc09bc8ccaf8"

      def install
        bin.install "sigil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zendesk/sigil/releases/download/v0.8.1/sigil_0.8.1_Linux_arm64.tar.gz"
      sha256 "c062e29c92f64707cb9f511a6333d28ecaaace77d6ea1bba0083d264bd57a6c7"

      def install
        bin.install "sigil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zendesk/sigil/releases/download/v0.8.1/sigil_0.8.1_Linux_x86_64.tar.gz"
      sha256 "d9318b4ee1ed0faeb10ec2bbbc41f1e08afd2bcbcd5fa11272f532550c8b0cf9"

      def install
        bin.install "sigil"
      end
    end
  end
end
