name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  main:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: zendesk/checkout@v2
      - name: Setup Golang
        uses: zendesk/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Setup cache
        uses: zendesk/cache@v2
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: ~/go/pkg/mod
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Taskfile
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          sudo mv ./bin/task /usr/local/bin
      - name: Test
        run: |
          task test
