name: CI
on:
  pull_request:
  push:
    branches: master

jobs:
  main:
    name: Test
    # runs-on: [self-hosted,zendesk-stable]
    steps:
      - name: Checkout source
        uses: zendesk/checkout@v2
      - name: Setup Golang
        uses: zendesk/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Setup cache
        uses: zendesk/cache@v2
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: ~/go/pkg/mod
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Taskfile
        uses: zendesk/go-task/setup-taskfile@master
      - name: Test
        run: |
          task build
