name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: zendesk/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: zendesk/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup cache
        uses: zendesk/cache@v2
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: ~/go/pkg/mod
          restore-keys: |
            ${{ runner.os }}-go-
      - name: install GoReleaser
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
          sudo mv ./bin/goreleaser /usr/local/bin/goreleaser
      - name: Run GoReleaser
        run: |
          goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
