name: Bazel Release

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Run build release binaries
        run: |
          bazel build --config cross:linux_amd64 :sigil_linux-amd64
          bazel build --config cross:windows_amd64 :sigil_windows-amd64
          bazel build --config cross:darwin_amd64 :sigil_darwin-amd64
      - name: Run build release container image
        run: |
          bazel run --config cross:linux_amd64 :push-release-image
          bazel run --config cross:linux_amd64 :push-major-release-image
          bazel run --config cross:linux_amd64 :push-minor-release-image
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bazel-bin/sigil_linux-amd64.tar.gz
            bazel-bin/sigil_darwin-amd64.tar.gz
            bazel-bin/sigil_windows-amd64.zip
