name: Bazel Linux Tests

defaults:
  run:
    shell: bash

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Run tests
        run: bazel test --config cross:linux_amd64 //...
      - name: Build
        run: bazel build --config cross:linux_amd64 :dev
      - name: Build container image
        run: bazel build --config cross:linux_amd64 :dev-image
      - name: Push dev container image
        run: bazel run --config cross:linux_amd64 :push-dev-image
        if: ${{ github.event_name != 'pull_request' }}
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.txt
          directory: ./bazel-bin/
          verbose: true
