name: Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-latest
          - macos-latest
          - macos-10.15
          - macos-11.0
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: install Session Manager Plugin
      run: ./scripts/install-helper.sh
    - name: Go Generate
      run: go generate ./...

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
